### ISSUE TITLE
bug: Final Appraisal functioning incorrect

### ISSUE THREAD

**Issue by italicninja** [ffxiv-teamcraft/simulator#17]
**Describe the bug**
When using Final Appraisal in the simulator the functionality is different than when in game

Using the Leather Macro here:
https://ffxivteamcraft.com/simulator/27743/33330/ZByhw59RaUbiKDrLhqQp

The simulator show the macro will succeed whereas in game the macro fails after the FA step into Delicate Synthesis. 

This is likely due to how FA interacts with Manipulation

**Comment by Supamiu** [comment]
Hey, thank you for the report.

Can you add your stats please so I can reproduce properly?

**Comment by italicninja** [comment]
Base stats are:
Craft: 2439
Control: 2475
CP: 556

**Comment by ayyaruq** [comment]
@Metra1337 as far as I can tell Final Appraisal functions properly with Manipulation now. Your rotation breaks for other reasons, notably using a 10 dura action under manip with 10 dura left (so manip can't refund dura as it already hits 0), but FA itself isn't ticking manip or refunding dura which should match the game. Are you able to verify it's working as you expect now?

**Comment by italicninja** [comment]
Yeah It looks good!
