### ISSUE TITLE
Why is the Excellent Step State's rate 0.4?

### ISSUE THREAD

**Issue by Tnze** [ffxiv-teamcraft/simulator#49]
Just curious, is the probability so high?
https://github.com/ffxiv-teamcraft/simulator/blob/b0996954fc948f9e240869783e73b4b14e59f423/src/simulation/simulation.ts#L441-L443

**Comment by Supamiu** [comment]
That's probably a mistake and should be 0.04, it's only used for probabilistic simulation tho, which is meant to be used for reliability report :)
