### ISSUE TITLE
Recommended stats

### ISSUE THREAD

**Issue by Igie** [ffxiv-teamcraft/simulator#6]
Not really an issue, more of curiosity of mine. How do you get recommended stats and real recipe levels for given recipe level in game, is there only all recipe database, datamining or could it be calculated?

**Comment by Supamiu** [comment]
It has to be datamined, suggested craftsmanship and suggested control are inside the RecipeLevelTable. There's no way to guess it.

**Comment by Igie** [comment]
Yes, thank you, I just did some datamining, also found CraftLevelDifference. How about recipe levels? I can't seem to find them anywhere 

Edit: just figured by myself it's index in RecipeLevelTable
