### ISSUE TITLE
Wrong progress and quality efficiency

### ISSUE THREAD

**Issue by Kuraiko55** [ffxiv-teamcraft/simulator#9]
Hey,

hopefully I didn't see this wrong, in which case I'm sorry, but from my view it seems this line in the simulator gets wrong values:
Progress per 100% efficiency: XXX Quality per 100% efficiency: XXX

To show you what I mean here are three screenshots.
First one of the simulator showing progress efficiency 270 and quality efficiency 310.
Second one of my InGame menu showing 360 and 621.
Third one the same menu and recipe at the second last step. If you believe the simulator, I'd need 'Careful Synthesis II' two times to finish, but I actually need only one.
So I can very well put another command in between without failing the recipe.

<img width="960" alt="chrome_2019-10-05_18-21-57" src="https://user-images.githubusercontent.com/56200847/66257966-d328e600-e79f-11e9-9baf-611304c30749.png">

![ffxiv_dx11_2019-10-05_18-36-11](https://user-images.githubusercontent.com/56200847/66257968-d7550380-e79f-11e9-8202-0487b5c1a4ed.jpg)

![ffxiv_dx11_2019-10-05_18-22-13](https://user-images.githubusercontent.com/56200847/66257972-dc19b780-e79f-11e9-8c00-4aeebdd6aa14.jpg)

**Comment by Supamiu** [comment]
Hi, thank you for your report,

Can you please make sure that your level ingame matches the level you entered inside the simulator's configuration?
